// muebleriaValadezFront/src/app/menu/menu.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent {
  constructor(private router: Router) {

  }
  menuPrincipal(): boolean {
    return sessionStorage.getItem('idRol') === null;
  }
  menuAdministrador(): boolean {
    if (sessionStorage.getItem('idRol') !== null && sessionStorage.getItem('idRol') ==='1') {
    return true;
    }else{
      return false;
    }
  }
  menuCliente(): boolean {
    if (sessionStorage.getItem('idRol') !== null && sessionStorage.getItem('idRol') ==='3') {
      return true;
      }else{
        return false;
      }
  }
  menuEmpleadoPedidos(): boolean {
    if (sessionStorage.getItem('idRol') !== null && sessionStorage.getItem('idRol') ==='10002') {
      return true;
      }else{
        return false;
      }
  }
  menuEmpleadoVentas(): boolean {
    if (sessionStorage.getItem('idRol') !== null && sessionStorage.getItem('idRol') ==='2') {
      return true;
      }else{
        return false;
      }
  }
  logOut(): void {
sessionStorage.removeItem('idUsuario');
sessionStorage.removeItem('idCliente');
sessionStorage.removeItem('idEmpleado');
sessionStorage.removeItem('email');
sessionStorage.removeItem('nombre');
sessionStorage.removeItem('idPersona');
sessionStorage.removeItem('idDireccionSucursal');
sessionStorage.removeItem('idRol');
sessionStorage.removeItem('rfc');
sessionStorage.removeItem('rol');
sessionStorage.removeItem('sucursal');
sessionStorage.removeItem('telefono');
this.router.navigateByUrl('/auth');
  }
}

<nav class="navbar navbar-expand-lg navbar-dark fixed-top">
  <img
    src="assets/img/Logo Negro.png"
    class="img-fluid"
    alt="Valadez Logo"
    style="height: 60px; margin-left: 2%"
  />
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNav"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <div *ngIf="menuPrincipal()" style="display: flex; padding: 0">
        <li class="nav-item" >
            <a class="nav-link" routerLinkActive="active" routerLink="shop">
              <button class="btn text-white text-left rounded">
                <span>Productos</span>
              </button>
            </a>
          </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" routerLink="us">
            <button class="btn text-white text-left rounded">
              <span>Sobre Nosotros</span>
            </button>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" routerLink="contact">
            <button class="btn text-white text-left rounded">
              <span>Contacto</span>
            </button>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" routerLink="auth">
            <button class="btn text-white text-left rounded">
              <span>Iniciar sesión</span>
            </button>
          </a>
        </li>
      </div>
      <div style="display: flex; padding: 0" *ngIf="menuAdministrador()">
        <li class="nav-item">
          <a
            class="nav-link"
            routerLinkActive="active"
            routerLink="dashboardAdministrador"
          >
            <button class="btn text-white text-left rounded">
              <span>Dashboard</span>
            </button>
          </a>
        </li>
        <div class="dropdown">
          <li class="nav-item">
            <a class="nav-link" routerLinkActive="active" [class.active]="isActive('insumos') || isActive('productos') || isActive('inventario')">
              <button class="btn text-white text-left rounded">
                <span>Producción</span>
              </button>
            </a>
          </li>
          <div class="dropdown-content">
            <li class="nav-item">
              <a class="nav-link" routerLinkActive="active" routerLink="insumos">
                <button class="btn text-white text-left rounded">
                  <span>Insumos</span>
                </button>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" routerLinkActive="active" routerLink="productos">
                <button class="btn text-white text-left rounded">
                  <span>Productos</span>
                </button>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" routerLinkActive="active" routerLink="inventario">
                <button class="btn text-white text-left rounded">
                  <span>Inventario</span>
                </button>
              </a>
            </li>
          </div>
        </div>
        <!-- 
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" routerLink="insumos">
            <button class="btn text-white text-left rounded">
              <span>Insumos</span>
            </button>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" routerLink="productos">
            <button class="btn text-white text-left rounded">
              <span>Productos</span>
            </button>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" routerLink="auth">
            <button class="btn text-white text-left rounded">
              <span>Inventario</span>
            </button>
          </a>
        </li> -->
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" routerLink="proveedores">
            <button class="btn text-white text-left rounded">
              <span>Proveedores</span>
            </button>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" routerLink="users">
            <button class="btn text-white text-left rounded">
              <span>Usuarios</span>
            </button>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" routerLink="auth">
            <button class="btn text-white text-left rounded">
              <span>Sucursales</span>
            </button>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" routerLink="auth">
            <button class="btn text-white text-left rounded">
              <span>Ventas</span>
            </button>
          </a>
        </li>
      </div>
      <div style="display: flex; padding: 0" *ngIf="menuEmpleadoVentas()">
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" routerLink="auth">
            <button class="btn text-white text-left rounded">
              <span>Inicio</span>
            </button>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" routerLink="auth">
            <button class="btn text-white text-left rounded">
              <span>Ventas</span>
            </button>
          </a>
        </li>
      </div>
      <div style="display: flex; padding: 0" *ngIf="menuEmpleadoPedidos()">
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" routerLink="auth">
            <button class="btn text-white text-left rounded">
              <span>Inicio</span>
            </button>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" routerLink="auth">
            <button class="btn text-white text-left rounded">
              <span>Pedidos</span>
            </button>
          </a>
        </li>
      </div>
      <div style="display: flex; padding: 0" *ngIf="menuCliente()">
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" routerLink="auth">
            <button class="btn text-white text-left rounded">
              <span>Inicio</span>
            </button>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" routerLink="auth">
            <button class="btn text-white text-left rounded">
              <span>Pedidos</span>
            </button>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" routerLink="auth">
            <button class="btn text-white text-left rounded">
              <span>Compras</span>
            </button>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLinkActive="active" routerLink="profile">
            <button class="btn text-white text-left rounded">
              <span>Administrar cuenta</span>
            </button>
          </a>
        </li>
      </div>
      <li class="nav-item align-content-center">
            <a class="nav-link" routerLinkActive="active">
              <button class="btn text-white text-left rounded" data-bs-toggle="modal" data-bs-target="#cartModal">
                <span><i class="fa fa-shopping-cart"></i></span>
              </button>
            </a>
          </li>
      <li class="nav-item" *ngIf="!menuPrincipal()" (click)="logOut()">
        <a class="nav-link" routerLinkActive="active" routerLink="auth">
          <button class="btn text-white text-left rounded">
            <span><i class="fas fa-sign-out-alt"></i></span>
          </button>
        </a>
      </li>            
    </ul>
  </div>

</nav><br><br>
<!-- Modal -->
<div class="modal fade" id="cartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title text-center" id="exampleModalLabel">Carrito de compras</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h2 class="text-center text-uppercase" *ngIf="cartItems.length === 0">Aún no haz agregado nada al carrito</h2>
        <div *ngFor="let item of cartItems">
        <div class="card mb-3" style="max-width: 540px;">
          <div class="row g-0">
            <div class="col-md-4">
              <ng-container *ngIf="item.foto == ''">
                <img src="../../assets/img/logo.jpg" class="img-fluid rounded-start" alt="logo">  
              </ng-container>
              <ng-container *ngIf="item.foto != '' || item.foto">
                <img src="{{item.foto}}" class="img-fluid rounded-start" alt="{{item.nombreProducto}}">  
              </ng-container>
            </div>
            <div class="col-md-8">
              <div class="row">
                <div class="card-body">
                  <h3 class="card-title">{{item.nombreProducto}}</h3>
                  <h4 class="card-text text-muted">Agregaste {{item.cantidad}} pz(s)</h4>
                  <button class="btn btn-danger btn-sm" (click)="removeOneCart(item)">
                    Remover piezas <i class="fas fa-minus"></i>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
      <div class="modal-footer">
        <div *ngIf="cartItems.length > 0">
          <button data-bs-toggle="modal" class="btn btn-success" data-bs-dismiss="modal" data-bs-target="#finVenta" (click)="checkSession();">
            Finalizar pedido <i class="fa fa-cart-arrow-down"></i>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

</nav>
<br /><br />

// muebleria-valadez-react/src/components/Menu.jsx
/**
 * @fileoverview Menu component
 * @returns MenuComponent
 * @imports N/A
 * @exports Menu
 * @requires N/A
 * @version 1.0.0
 * @since 1.0.0
 * @description Componente que muestra la barra de navegación a los módulos
 *             correspondientes
 * @created 2021-11-24
 * @modified 2021-11-24
 */


const Menu = ({items, 
              eliminarItem, 
              vaciarCarrito, 
              getTotalCart, 
              cards, 
              addresses, 
              registerOrder, 
              cerrarSesion
              }) => {
  // Funcion que comprueba si el usuario esta logueado
  let isLogged = () => {
    if (sessionStorage.getItem('idCliente') != null ) {
      return true;
    } else {
      return false;
    }
  }

  return (
    <>
      {/* NavBar */}
      <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
        <div className="container-fluid">
          <a className="navbar-brand" href="/"><img src="../../public/Logo Negro.png"
            alt="Valadez Logo"
            style={{ height: "60px", marginLeft: "2%" }} /></a>
          <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
          </button>

          <div className="collapse navbar-collapse" id="navbarColor02">
            <ul className="navbar-nav me-auto">
              <li className="nav-item">
                <a className="nav-link active" href="/shop">Productos
                  <span className="visually-hidden">(current)</span>
                </a>
              </li>

              {/* Si el usuario esta logueado, mostrar las opciones del carrito y cerrar sesión */
                isLogged() ?
                  <>
                  <li className="nav-item">
                      <a className="nav-link" href="/myOrders">Mis Pedidos</a>
                    </li>
                    <li className="nav-item">
                      <a className="nav-link" data-bs-toggle="modal" data-bs-target="#finVenta" ><i className="fas fa-shopping-cart"></i></a>
                    </li>
                    <li className="nav-item">
                      <a className="nav-link" onClick={cerrarSesion}>Cerrar Sesión</a>
                    </li>
                  </>
                  :
                  <>
                    {/* Si el usuario no esta logueado, mostrar los modulos informativos e inicio de sesión */}
                    <li className="nav-item">
                      <a className="nav-link active" href="/us">Sobre nosotros</a>
                    </li>
                    <li className="nav-item">
                      <a className="nav-link active" href="/contact">Contacto</a>
                    </li>
                    <li className="nav-item">
                      <a className="nav-link" data-bs-toggle="modal" data-bs-target="#finVenta"><i className="fas fa-shopping-cart"></i></a>
                    </li>s
                    <li className="nav-item">
                      <a className="nav-link active" href="/">Iniciar Sesión</a>
                    </li>
                  </>
              }
            </ul>
          </div>
        </div>
      </nav>
      {/* Ventana modal para mostrar el carrito */}
      <div className="modal fade" id="finVenta"  role="dialog"  aria-hidden="true">
        <div className="modal-dialog" role="document">
          <div className="modal-content">
            <div className="modal-header">
              <h2 className="modal-title text-center" >Confirmar Compra</h2>
              <button type="button" className="close btn btn-danger" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div className="modal-body text-center">
                <h4>Confirma tus datos de compra</h4> 
                </div>
            <div className="modal-body">
                <div className="row" >
                    {
                        items.length === 0 ?
                        <div className="col-md-12">
                            <div className="alert alert-warning" role="alert">
                                No hay productos en el carrito
                            </div>
                        </div>
                        :
                        <>
                        <div className="row">
                          {// Recorre el carrito para mostrar los productos
                          items.map((item, index) => (
                            <div className="col-md-6" key={index} >
                              <div className="card mb-3" style={{ maxWidth: '540px' }}>
                                <div className="row g-0">
                                  <div className="col-md-4">
                                    <img src={item.foto} className="img-fluid rounded-start" alt="..." />
                                  </div>
                                  <div className="col-md-8">
                                    <div className="card-body">
                                      <h5 className="card-title">{item.nombreProducto}</h5>
                                      <p className="card-text text-success">$ {item.precioVenta} MXN</p>
                                      <p className="card-text"><small className="text-muted">{item.cantidad} pieza(s)</small></p>
                                      <button className="btn btn-danger" onClick={() => eliminarItem(item)}>-</button>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <br />
                            </div>
                          ))}
                          </div>
                          <div className="row">                
                      <div className="col-md-12">
                        <form>
                          <div className="form-group">
                              <div className="row">

                                {sessionStorage.getItem('idCliente') != null ?
                                  <>
                                    <div className="col-6">
                                      <label htmlFor="tarjeta" className="col-form-label">Escoge tu tarjeta</label><br />
                                      <select className="form-select" id="tarjeta" name="tarjeta" >
                                        {
                                          cards.map(card => (
                                            <option key={card.idTarjeta} value={card.idTarjeta}> 
                                              {card.numeroTarejta}
                                            </option>
                                          ))
                                        }
                                      </select>
                                    </div>
                                    <div className="col-6">
                                      <label htmlFor="direccion" className="col-form-label text-center">Escoge tu direccion</label><br />
                                      <select className="form-select text-uppercase" id="direccion" name="direccion">
                                        {
                                          addresses.map(address => (
                                            <option key={address.idDireccion} value={address.idDireccion}> 
                                              {address.calle} #{address.noExt} 
                                            </option>
                                          ))
                                        }
                                      </select>
                                    </div>
                                  </>
                                  :
                                  <>
                                  <center>
                                    <div className="col-md-12">
                                      <p><b>Tienes que iniciar sesión para poder ver tus direcciones y tarjetas </b> </p>
                                    </div>
                                  </center>
                                  </>
                                }
                                </div>
                                <br />
                                <div className="row">
                                  <div className="col-6">
                                    <p className="h5 text-primary"> Total: </p>
                                  </div>
                                  <div className="col-6">
                                      <p className="text-success h5">$ {getTotalCart()} MXN</p>
                                  </div>
                              </div>
                            </div>
                        </form>
                      </div>
                      <div className="modal-footer">
                      <button type="button" className="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
                        <button type="button" className="btn btn-warning" onClick={vaciarCarrito}>Limpiar Carrito <i className="fa fa-shopping-cart"></i></button>
                        <button type="button" className="btn btn-success" data-bs-dismiss="modal" onClick={registerOrder}>Realizar Pedido</button>
                      </div>
                </div>
                        </>
                        }
                      </div>
            </div>
          </div>
        </div>
      </div>
  {/* Termina ventana modal del carrito */}

    </>
  )
}

export default Menu
