// muebleria-valadez-react/src/components/SignUp/SignUp.jsx
//import React from 'react'

import { useState } from "react";
import Swal from "sweetalert2";
import axios from 'axios';
import './SignUp.css'
import { useNavigate } from "react-router-dom";
import SHA512 from 'crypto-js/sha512';
const SignUp = () => {

    const [isPasswordVisible, setIsPasswordVisible] = useState(false);

    const changeIcon = () => {
        const passwordInput = document.getElementById('txtPassword');
        const eyeIcon = document.getElementById('eyeIcon');

        if (isPasswordVisible) {
            passwordInput.type = 'password';
            eyeIcon.classList.remove('fa-eye');
            eyeIcon.classList.add('fa-eye-slash');
        } else {
            passwordInput.type = 'text';
            eyeIcon.classList.remove('fa-eye-slash');
            eyeIcon.classList.add('fa-eye');
        }

        setIsPasswordVisible(!isPasswordVisible);
    };

    const navigate = useNavigate();
    const [formData, setFormData] = useState({
        nombre: '',
        apellidoP: '',
        apellidoM: '',
        telefono: '',
        correo: '',
        password: '',
        password2: '',
    });

    const apiUrl = 'https://localhost:7010/auth/Auth';

    const signUp = async () => {
        const { nombre, apellidoP, apellidoM, telefono, correo, password } = formData;

        const body = {
            email: correo,
            password: SHA512(password).toString(),
            persona: {
                nombres: nombre,
                apellidoPaterno: apellidoP,
                apellidoMaterno: apellidoM,
                telefono: telefono,
            },
        };

        try {
            const response = await axios.post(apiUrl, body, { responseType: 'text' });
            // Manejar la respuesta después de registrarse exitosamente
            console.log(response);

            Swal.fire({
                icon: 'success',
                title: '¡Usuario creado!',
                text: '¡Bienvenido!',
                timer: 3000,
                timerProgressBar: true,
                showConfirmButton: false,
            }).then(() => {
                // Redirigir al usuario a la página de inicio de sesión (/auth) después de mostrar el mensaje de éxito
                // Reemplaza la redirección con el método adecuado para tu enrutamiento
                navigate('/login');
            });
        } catch (error) {
            console.error('Error al crear usuario:', error);

            Swal.fire({
                icon: 'error',
                title: '¡Error a la hora de crear usuario!',
                text: 'Ocurrió un error al crear el usuario.',
            });
        }
    };

    const userFind = async (correo) => {
        const findUrl = 'https://localhost:7010/auth/Auth/userFind';
        const body = {
            email: correo,
        };

        try {
            const result = await axios.post(findUrl, body, { responseType: 'text' });
            const exists = JSON.parse(result.data);
            if (exists.exists) {
                Swal.fire({
                    icon: 'warning',
                    title: '¡Elija otro correo!',
                    text: 'El correo ingresado ya se encuentra registrado.',
                    confirmButtonColor: '#20a124',
                    confirmButtonText: 'Aceptar',
                });
            } else {
                // Realizar el registro del usuario si el correo no existe
                signUp();
            }
        } catch (error) {
            console.error('Error al buscar usuario:', error);

            Swal.fire({
                icon: 'error',
                title: '¡Error a la hora de crear usuario!',
                text: 'Ocurrió un error al crear el usuario.',
            });
        }
    };

    const onSubmit = (e) => {
        e.preventDefault();
        console.log(formData);
        if (formData.password !== formData.password2) {
            Swal.fire({
                icon: 'info',
                title: 'Contraseñas incorrectas',
                text: 'Las contraseñas ingresadas no coinciden. Intente de nuevo.',
                confirmButtonColor: '#20a124',
                confirmButtonText: 'Aceptar',
            });
        } else if (formData.password === formData.password2) {
            userFind(formData.correo);
        }
    };

    const handleInputChange = (e) => {
        const { name, value } = e.target;
        setFormData({
            ...formData,
            [name]: value,
        });
    };

    return (
        <>
            <div className="cuerpo">
                <br />
                <div className="contenedor p-4 mt-5 shadow rounded">
                    <h2 id="tituloFormulario" className="text-center mt-1">Creación de cuenta</h2>
                    <br />
                    <form onSubmit={onSubmit}>
                        <div className="row mt-3">
                            <div className="form-group col-12 col-md-4">
                                <label className="form-label">Nombre</label>
                                <input required id="txtnombre"
                                    value={formData.nombre} // Vincula el valor del campo con el estado formData.nombre
                                    onChange={handleInputChange}
                                    minLength={3} maxLength={100} name="nombre" type="text" className="form-control form-control-lg" />
                            </div>
                            <div className="form-group col-12 col-md-4">
                                <label className="form-label">Apellido Paterno</label>
                                <input required id="txtAPaterno"
                                    value={formData.apellidoP} // Vincula el valor del campo con el estado formData.apellidoP
                                    onChange={handleInputChange}
                                    minLength={3} maxLength={100} name="apellidoP" type="text" className="form-control form-control-lg" />
                            </div>
                            <div className="form-group col-12 col-md-4">
                                <label className="form-label">Apellido Materno</label>
                                <input
                                    value={formData.apellidoM} // Vincula el valor del campo con el estado formData.apellidoM
                                    onChange={handleInputChange}
                                    name="apellidoM" id="txtAMaterno" type="text" className="form-control form-control-lg" />
                            </div>
                        </div>
                        <div className="row mt-2">
                            <div className="form-group col-12 col-md-4">
                                <label className="form-label">Teléfono</label>
                                <div className="input-group">
                                    <input
                                        value={formData.telefono} // Vincula el valor del campo con el estado formData.telefono
                                        onChange={handleInputChange}
                                        required name="telefono" minLength={10} maxLength={20} id="txtTelefono" type="text" className="form-control form-control-lg" />
                                    <div className="input-group-append">
                                        <span className="input-group-btn">
                                            <a id="btnPhone" className="botonTelefono">
                                                <span className="fa fa-question-circle"></span>
                                            </a>
                                        </span>
                                        <div className="tooltip">
                                            El registro de un número télefonico es con el propósito de medio de contacto en un envío de compra.
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="form-group col-12 col-md-8">
                                <label className="form-label">E-mail</label>
                                <input
                                    value={formData.correo} // Vincula el valor del campo con el estado formData.email
                                    onChange={handleInputChange}
                                    required name="correo" minLength={3} maxLength={100} id="txtEmail" type="text" className="form-control form-control-lg" />
                            </div>
                        </div>
                        <div className="row mt-2">
                            <div className="form-group col-12 col-md-6">
                                <label className="form-label">Contraseña</label>
                                <div className="input-group">
                                    <input required name="password"
                                        value={formData.password} // Vincula el valor del campo con el estado formData.password
                                        onChange={handleInputChange}
                                        id="txtPassword" minLength={3} maxLength={50} type="password" className="form-control form-control-lg" />
                                    <div className="input-group-append">
                                        <button onClick={changeIcon} type="button" id="btnPassword" className="botonContrasena">
                                            <i
                                                id="eyeIcon"
                                                className={isPasswordVisible ? 'fa fa-eye-slash' : 'fa fa-eye'}
                                                style={{ backgroundColor: 'transparent' }}></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <div className="form-group col-12 col-md-6">
                                <label className="form-label">Repita su contraseña</label>
                                <input required
                                    value={formData.password2} // Vincula el valor del campo con el estado formData.password2
                                    onChange={handleInputChange}
                                    id="txtPassword2" name="password2" minLength={3} maxLength={50} type="password" className="form-control form-control-lg" />
                            </div>
                        </div>
                        <div className="row mt-2">
                            <div className="form-group col-12 col-md-6 mt-4">
                                <button id="botonCrear" type="submit" className="btn btn-lg form-control text-center">CREAR CUENTA</button>
                            </div>
                            <div className="form-group col-12 col-md-6">
                                <a className="text-center text-white" href="/login">
                                    <button id="botonVolver" type="button" className="btn btn-lg form-control mt-4">REGRESAR</button>
                                </a>
                            </div>
                        </div>

                    </form>
                </div><br /><br />
            </div>


        </>
    )
}

export default SignUp

// muebleriaValadezFront/src/app/login/signup/signup.component.ts
import {
  Component,
  ElementRef,
  ViewChild,
  Renderer2,
  OnInit,
} from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { SignupService } from './signup.service';
import Swal from 'sweetalert2';
import { LoadingService } from 'src/app/loading.service';
import * as crypto from 'crypto-js';
import { Router } from '@angular/router';


@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css'],
})
export class SignupComponent implements OnInit {
  signUpForm!: FormGroup;
  constructor(
    private fb: FormBuilder,
    private renderer: Renderer2,
    private signUpService: SignupService,
    private loadingService: LoadingService,
    private router: Router
  ) { }

  isPasswordVisible = false;
  @ViewChild('asIcon') icono!: ElementRef;
  @ViewChild('asPassword') password!: ElementRef;
  ngOnInit(): void {
    // Inicializa el formulario sin controles individuales en el constructor
    this.signUpForm = this.fb.group({});

    // Agrega los controles individuales con sus validadores en el método ngOnInit
    this.signUpForm.addControl(
      'nombre',
      this.fb.control('', [
        Validators.required,
        Validators.minLength(3),
        Validators.maxLength(100),
      ])
    );
    this.signUpForm.addControl(
      'apellidoP',
      this.fb.control('', [
        Validators.required,
        Validators.minLength(3),
        Validators.maxLength(50),
      ])
    );
    this.signUpForm.addControl(
      'apellidoM',
      this.fb.control('', [Validators.minLength(3), Validators.maxLength(50)])
    );
    this.signUpForm.addControl(
      'telefono',
      this.fb.control('', [
        Validators.required,
        Validators.minLength(10),
        Validators.maxLength(20),
      ])
    );
    this.signUpForm.addControl(
      'email',
      this.fb.control('', [
        Validators.required,
        Validators.email,
        Validators.minLength(3),
        Validators.maxLength(50),
      ])
    );
    this.signUpForm.addControl(
      'password',
      this.fb.control('', [
        Validators.required,
        Validators.minLength(3),
        Validators.maxLength(50),
      ])
    );
    this.signUpForm.addControl('password2', this.fb.control(''));
  }
  onSubmit() {
    console.log(this.signUpForm.get('password')?.value);
    console.log(this.signUpForm.get('password2')?.value);
    if (this.signUpForm.valid) {
      if(this.signUpForm.get('password')?.value != this.signUpForm.get('password2')?.value){
        Swal.fire({
          icon: 'info',
          title: 'Contraseñas incorrectas',
          text: 'Las contraseñas ingresas no coinciden. Intente de nuevo.',
          confirmButtonColor: '#20a124',
          confirmButtonText: 'Aceptar',
        });
      }
      else if (
        this.signUpForm.get('password')?.value ==
        this.signUpForm.get('password2')?.value
      ) {
        this.signUpService.userFind(this.signUpForm.get('email')?.value)
          .then((result: any) => {
            // 'result' contiene el resultado como texto (puede ser "true" o "false")
            const exists = JSON.parse(result); // Convierte el texto a un valor booleano
            console.log(exists.exists);
            if (exists.exists) {
              Swal.fire({
                icon: 'warning',
                title: '¡Elija otro correo!',
                text: 'El correo ingresado ya se encuentra registrado.',
                confirmButtonColor: '#20a124',
                confirmButtonText: 'Aceptar',
              });
            } else {
              this.loadingService.show();
              const nombre = this.signUpForm.get('nombre')?.value;
              const apellidoP = this.signUpForm.get('apellidoP')?.value;
              const apellidoM = this.signUpForm.get('apellidoM')?.value;
              const telefono = this.signUpForm.get('telefono')?.value;
              const email = this.signUpForm.get('email')?.value;
              const password = crypto
                .SHA512(this.signUpForm.get('password')?.value)
                .toString();
              this.loadingService.show();
              this.signUpService
                .signUp(nombre, apellidoP, apellidoM, telefono, email, password)
                .then((response: any) => {

                  Swal.fire({
                    icon: 'success',
                    title: '¡Usuario creado!',
                    text: '¡Bienvenido!',
                    timer: 3000, // 3 segundos
                    timerProgressBar: true, // Muestra una barra de progreso durante el tiempo de espera
                    showConfirmButton: false // No muestra el botón de confirmación para cerrar el mensaje
                  }).then(() => {
                    // Redirigir al usuario a la página de inicio de sesión (/auth) después de mostrar el mensaje de éxito
                    this.router.navigateByUrl('/auth');
                  });
                })
                .catch((error: any) => {

                  Swal.fire({
                    icon: 'error',
                    title: '¡Error a la hora de crear usuario!',
                    text: 'Ocurrió un error al crear el usuario.',
                  });
                })
                .finally(() => {
                  this.loadingService.hide(); // Ocultar el loader, tanto si hay éxito como error
                });
            }
          })
          .catch((error: any) => {
            Swal.fire({
              icon: 'error',
              title: '¡Error a la hora de crear usuario!',
              text: 'Ocurrió un error al crear el usuario.',
            });
          });

      }
    }
  }

  changeIcon(): void {
    const asIcon = this.icono.nativeElement;
    const asPassword = this.password.nativeElement;

    if (this.isPasswordVisible) {
      this.renderer.setAttribute(asPassword, 'type', 'password');
      this.renderer.removeClass(asIcon, 'fa-eye-slash');
      this.renderer.addClass(asIcon, 'fa-eye');
      console.log(asIcon);
    } else {
      this.renderer.setAttribute(asPassword, 'type', 'text');
      this.renderer.removeClass(asIcon, 'fa-eye');
      this.renderer.addClass(asIcon, 'fa-eye-slash');
      console.log(asIcon);
    }

    this.isPasswordVisible = !this.isPasswordVisible;
  }

  // Validaciones del formulario crear cuenta antes de enviarlo
  initForm(): FormGroup {
    return this.fb.group({
      nombre: ['', [Validators.required, Validators.minLength(3), Validators.maxLength(100)]],
      apellidoP: ['', [Validators.required, Validators.maxLength(50)]],
      telefono: ['', [Validators.required, Validators.minLength(10), Validators.maxLength(20)]],
      email: ['', Validators.required, Validators.minLength(10), Validators.maxLength(100)],
      password:['', Validators.required, Validators.minLength(3)]
    });
  }
}

<div class="body">
  <br>
    <div class="container p-4 mt-5 shadow rounded">
        <h2 id="title" class="text-center mt-1">Creación de cuenta</h2>
        <br>
        <form
              [formGroup]="signUpForm"
              (ngSubmit)="signUpForm.valid && onSubmit()"
            >
        <div class="row mt-3">
            <!-- Nombre input -->
            <div class="form-group col-12 col-md-1"></div>
            <div class="form-group col-12 col-md-4">
                <label class="form-label" for="txtName">Nombre</label>
                <input id="txtnombre"
                type="text"
                class="form-control form-control-lg"
                formControlName="nombre"/>
                <div *ngIf="signUpForm.get('nombre')?.touched && 
                            signUpForm.get('nombre')?.errors?.['required']" class="text-danger">
                    Este campo es requerido
                </div>
                <div *ngIf="signUpForm.get('nombre')?.touched && 
                            signUpForm.get('nombre')?.errors?.['minlength']" class="text-danger">
                    El nombre debe ser más largo que
                    {{signUpForm.get('nombre')?.errors?.['minlength']?.requiredLength}} 
                    letras
                </div>
                <div *ngIf="signUpForm.get('nombre')?.touched && 
                            signUpForm.get('nombre')?.errors?.['maxlength']" class="text-danger">
                    El nombre debe ser menor que
                    {{signUpForm.get('nombre')?.errors?.['maxlength']?.requiredLength}} 
                    letras
                </div>
            </div>

            <!-- Apellido Paterno input -->
            <div class="form-group col-12 col-md-3">
                <label class="form-label" for="txtAPaterno">Apellido Paterno</label>
                <input id="txtAPaterno" type="text" class="form-control form-control-lg" formControlName="apellidoP" />
                <div *ngIf="signUpForm.get('apellidoP')?.touched && 
                            signUpForm.get('apellidoP')?.errors?.['required']" class="text-danger">
                    Este campo es requerido
                </div>
                <div *ngIf="signUpForm.get('apellidoP')?.touched && 
                            signUpForm.get('apellidoP')?.errors?.['minlength']" class="text-danger">
                    El apellido debe ser más largo que
                    {{signUpForm.get('apellidoP')?.errors?.['minlength']?.requiredLength}} 
                    letras
                </div>
                <div *ngIf="signUpForm.get('apellidoP')?.touched && 
                            signUpForm.get('apellidoP')?.errors?.['maxlength']" class="text-danger">
                    El apellido debe ser menor que
                    {{signUpForm.get('apellidoP')?.errors?.['maxlength']?.requiredLength}} 
                    letras
                </div>
            </div>

            <!-- Apellido Materno input -->
            <div class="form-group col-12 col-md-3">
                <label class="form-label" for="txtAMaterno">Apellido Materno</label>
                <input id="txtAMaterno" type="text" class="form-control form-control-lg" formControlName="apellidoM" />
            </div>
            <div class="form-group col-12 col-md-1"></div>

            <!-- Telefono input -->
            <div class="form-group col-12 col-md-1"></div>

            <div class="form-group col-12 col-md-4 mt-4">
                <label class="form-label" for="txtTelefono">Teléfono</label>
                <div class="input-group">
                    <input id="txtTelefono" type="text" class="form-control form-control-lg" formControlName="telefono" />
                    <div *ngIf="signUpForm.get('telefono')?.touched && 
                            signUpForm.get('telefono')?.errors?.['required']" class="text-danger">
                          Este campo es requerido
                    </div>
                    <div *ngIf="signUpForm.get('telefono')?.touched && 
                            signUpForm.get('telefono')?.errors?.['minlength']" class="text-danger">
                          El teléfono debe contar o bien ser mayor a
                          {{signUpForm.get('telefono')?.errors?.['minlength']?.requiredLength}} 
                          dígitos.
                    </div>
                    <div *ngIf="signUpForm.get('telefono')?.touched && 
                            signUpForm.get('telefono')?.errors?.['maxlength']" class="text-danger">
                          El teléfono debe ser menor que
                          {{signUpForm.get('telefono')?.errors?.['maxlength']?.requiredLength}} 
                          letras
                    </div>
                    <div class="input-group-append">
                        <span class="input-group-btn">
                            <a id="btnPhone" class="btn">
                                <span class="fa fa-question-circle"></span>
                            </a>
                        </span>
                        <div class="tooltip">
                            El registro de un número télefonico es con el próposito de medio de contacto en un envío de compra.
                        </div>
                    </div>
                </div>
            </div>


            <!-- Número input
            <div class="form-group col-12 col-md-2 mt-4">
                <label class="form-label" for="txtNumero">Número</label>
                <input id="txtNumero" type="text" class="form-control form-control-lg" name="" />
            </div>

            // Calle input
            <div class="form-group col-12 col-md-4 mt-4">
                <label class="form-label" for="txtCalle">Calle</label>
                <div class="input-group">
                    <input id="txtCalle" type="text" class="form-control form-control-lg" name="" />
                    <div class="input-group-append">
                        <span class="input-group-btn">
                            <a id="btnAddress" class="btn">
                                <span class="fa fa-question-circle"></span>
                            </a>
                        </span>
                        <div class="tooltip">
                            El registro de un domicilio es con el próposito de determinar la dirección de envío de una compra.
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group col-12 col-md-1"></div>

            // Colonia input
            <div class="form-group col-12 col-md-1"></div>
            <div class="form-group col-12 col-md-4 mt-4">
                <label class="form-label" for="txtColonia">Colonia</label>
                <input id="txtColonia" type="text" class="form-control form-control-lg" name="" />
            </div>

            // CodePostal input
            <div class="form-group col-12 col-md-2 mt-4">
                <label class="form-label" for="txtCP">Código Postal</label>
                <input id="txtCp" type="number" class="form-control form-control-lg" name="" />
            </div>

            // Ciudad input
            <div class="form-group col-12 col-md-4 mt-4">
                <label class="form-label" for="txtCiudad">Ciudad</label>
                <input id="txtCiudad" type="text" class="form-control form-control-lg" name="inpVille" />
            </div>
            <div class="form-group col-12 col-md-1"></div> -->

            <!-- Email input -->
            <div class="form-group col-12 col-md-6 mt-4">
                <label for="txtEmail" class="form-label">E-mail</label>
                <input id="txtEmail" type="text" class="form-control form-control-lg" formControlName="email">
              
                <div *ngIf="signUpForm.get('email')?.touched && 
                            signUpForm.get('email')?.errors?.['required']" class="text-danger">
                    Este campo es requerido.
                </div>
                <div *ngIf="signUpForm.get('email')?.touched && 
                            signUpForm.get('email')?.errors?.['minlength']" class="text-danger">
                    El correo debe ser más largo que
                    {{signUpForm.get('email')?.errors?.['minlength']?.requiredLength}} 
                    letras
                </div>
                <div *ngIf="signUpForm.get('email')?.touched && 
                            signUpForm.get('email')?.errors?.['maxlength']" class="text-danger">
                    El correo debe ser menor que
                    {{signUpForm.get('email')?.errors?.['maxlength']?.requiredLength}} 
                    letras
                </div>
            </div>
            <div class="form-group col-12 col-md-2 mt-4"></div>
            <!-- Password input -->
            <div class="form-group col-12 col-md-4 mt-4">
                <label class="form-label" for="txtPassword">Contraseña</label>
                <div class="input-group">
                <input #asPassword id="txtPassword" type="password" class="form-control form-control-lg" formControlName="password" />
                <div class="input-group-append">
                    <button type="button" id="btnPassword" class="btn btn-toggle-password" (click)="changeIcon()">
                        <i #asIcon class="fa fa-eye"></i>
                    </button>
                </div>
                </div>
                <div
                  *ngIf="
                    signUpForm.get('password')?.invalid &&
                    (signUpForm.get('password')?.dirty ||
                    signUpForm.get('password')?.touched)
                  "
                  class="text-danger"
                >
                  Contraseña es requerida.
                </div>
                <div
                  *ngIf="signUpForm.get('password')?.errors?.['minLength']"
                  class="text-danger"
                >
                  Debe ser mayor a 3 su longitud.
                </div>
                <div
                  *ngIf="signUpForm.get('password')?.errors?.['maxLength']"
                  class="text-danger"
                >
                  Debe ser menor a 50 su longitud.
                </div>
            </div>
            <!-- Password confirm input -->
            <div class="form-group col-12 col-md-4 mt-4">
                <label class="form-label" for="txtPassword2">Repita su contraseña</label>
                <input id="txtPassword2" type="password" class="form-control form-control-lg" formControlName="password2"/>
            </div>
            <div class="form-group col-12 col-md-1"></div>
            <!-- Submit buttons -->
            <div class="form-group col-12 col-md-3"></div>
            <div class="form-group col-12 col-md-3 mt-4">
                <button id="btnCreate" type="submit" class="btn btn-lg form-control text-center"  [disabled]="signUpForm.invalid">CREAR CUENTA</button>
            </div>
            <div class="form-group col-12 col-md-3">
                <a routerLink="/auth" routerLinkActive="router-link-active" class="text-center text-white">
                    <button id="btnBack" class="btn btn-lg form-control mt-4">REGRESAR</button>
                </a>
            </div>
            <div class="form-group col-12 col-md-3"></div>
        </div>
      </form>
    </div><br><br>
</div>
