// muebleriaValadezFront/src/app/footer/footer.component.ts
import { Component } from '@angular/core';
import Swal from 'sweetalert2'

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent {

  newsletter() {
    Swal.fire({
      title: '¡Muchas gracias!',
      text: 'Se ha registrado correctamente a nuestro newsletter. Agradecemos su confianza.',
      icon: 'success',
      showCancelButton: false,
      confirmButtonColor: '#28a745', // Color verde para el botón de éxito
      confirmButtonText: 'Aceptar',
      customClass: {
        confirmButton: 'btn-success' // Agrega la clase 'btn-success' al botón de éxito
      }
    });
  }
}

<footer class="bg-dark text-center text-white py-5">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <div class="row">
      <div class="col-6 col-md-2 mb-3">
        <h5>Secciones</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2">
            <a href="#" class="nav-link p-0 text-white" routerLink="products">Productos</a>
          </li>
          <li class="nav-item mb-2">
            <a href="#" class="nav-link p-0 text-white" routerLink="us">Sobre nosotros</a>
          </li>
          <li class="nav-item mb-2">
            <a href="#" class="nav-link p-0 text-white" routerLink="contact">Contacto</a>
          </li>
        </ul>
      </div>
      <div class="col-6 col-md-3 mb-3">
        <h5>Ayuda</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2">
            <a href="#" class="nav-link p-0 text-white">Preguntas frecuentes</a>
          </li>
          <li class="nav-item mb-2">
            <a href="#" class="nav-link p-0 text-white">Aviso de Privacidad</a>
          </li>
          <li class="nav-item mb-2">
            <a href="#" class="nav-link p-0 text-white">Términos y condiciones</a>
          </li>
        </ul>
      </div>
      <div class="col-md-5 offset-md-1 mb-3">
        <form>
          <h5>Suscríbete al newsletter</h5>
          <p>Entérate de nuestras novedades, beneficios y contenido exclusivo.</p>
          <div class="d-flex flex-column flex-sm-row w-100 gap-2">
            <label for="newsletter1" class="visually-hidden"
              >Dirección de correo</label
            >
            <input
              id="newsletter1"
              type="text"
              class="form-control"
              placeholder="Dirección de correo"
            />
            <button class="btn btn-secondary" type="button" (click)="newsletter()">Regístrate</button>
          </div>
        </form>
      </div>
    </div>
    <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
        <p>© 2023 Mueblería Valadez. Todos los derechos reservados.</p>
        <ul class="list-unstyled d-flex">
            <section class="mb-4">
            <!-- Facebook -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                <i class="fab fa-facebook-f"></i>
            </a>
            <!-- Twitter -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                <i class="fab fa-twitter"></i>
            </a>
            <!-- Google -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                <i class="fab fa-pinterest"></i>
            </a>

            <!-- Instagram -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                <i class="fa fa-envelope"></i>
            </a>
            <!-- Whatsapp -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                <i class="fab fa-whatsapp"></i>
            </a>
        </section>
        </ul>
    </div>
  </div>
  <!-- Grid container -->
</footer>

// muebleria-valadez-react/src/components/Footer/Footer.jsx
//import React from 'react'
import './Footer'
const Footer = () => {
    return (
        <>
            <footer className="bg-dark text-center text-white footer">
                <div className="container p-4 pb-0">
                    <div className="row">
                        <div className="col-6 col-md-2 mb-3">
                            <h1>Secciones</h1>
                            <ul className="nav flex-column">
                                <li className="nav-item mb-2">
                                    <a href="#" className="nav-link p-0 text-white anal">Productos</a>
                                </li>
                                <li className="nav-item mb-2">
                                    <a href="#" className="nav-link p-0 text-white anal">Sobre nosotros</a>
                                </li>
                                <li className="nav-item mb-2">
                                    <a href="#" className="nav-link p-0 text-white anal">Contacto</a>
                                </li>
                                <li className="nav-item mb-2">
                                    <a href="#" className="nav-link p-0 text-white anal">Crear cuenta</a>
                                </li>
                            </ul>
                        </div>
                        <div className="col-6 col-md-3 mb-3">
                            <h1>Ayuda</h1>
                            <ul className="nav flex-column">
                                <li className="nav-item mb-2">
                                    <a href="#" className="nav-link p-0 text-white anal">Preguntas frecuentes</a>
                                </li>
                                <li className="nav-item mb-2">
                                    <a href="#" className="nav-link p-0 text-white anal">Aviso de Privacidad</a>
                                </li>
                                <li className="nav-item mb-2">
                                    <a href="#" className="nav-link p-0 text-white anal">Términos y condiciones</a>
                                </li>
                                <li className="nav-item mb-2">
                                    <a href="#" className="nav-link p-0 text-white anal">Garantías</a>
                                </li>
                            </ul>
                        </div>
                        <div className="col-md-5 offset-md-1 mb-3">
                            <form >
                                <h1>Suscríbete al newsletter</h1>
                                <p className='pene'>Entérate de nuestras novedades, beneficios y contenido exclusivo.</p>
                                <div className="d-flex flex-column flex-sm-row w-100 gap-2">
                                    <label className="visually-hidden"
                                    >Dirección de correo</label
                                    >
                                    <input
                                        id="newsletter1"
                                        type="text"
                                        className="form-control"
                                        placeholder="Dirección de correo"

                                    />
                                    <button className="btn btn-secondary" type="submit">Regístrate</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div className="d-flex flex-column flex-sm-row justify-content-between py-2 my-4 border-top">
                        <p className='pene'>© 2023 Mueblería Valadez. Todos los derechos reservados.</p>
                        <ul className="list-unstyled d-flex">
                            <section className="mb-4">
                                <a className="btn btn-outline-light btn-floating m-1 anal" href="https://www.facebook.com/" role="button">
                                    <i className="fab fa-facebook-f"></i>
                                </a>

                                <a className="btn btn-outline-light btn-floating m-1 anal" href="https://twitter.com/" role="button">
                                    <i className="fab fa-twitter"></i>
                                </a>

                                <a className="btn btn-outline-light btn-floating m-1 anal" href="https://pinterest.com/" role="button">
                                    <i className="fab fa-pinterest"></i>
                                </a>


                                <a className="btn btn-outline-light btn-floating m-1 anal" href="https://gmail.com/" role="button">
                                    <i className="fa fa-envelope"></i>
                                </a>

                                <a className="btn btn-outline-light btn-floating m-1 anal" href="https://web.whatsapp.com/" role="button">
                                    <i className="fab fa-whatsapp"></i>
                                </a>
                            </section>
                        </ul>
                    </div>
                </div>

            </footer >
        </>

    )
}

export default Footer
