// muebleria-valadez-react/src/components/Pedidos/Pedidos.jsx
/**
 * @author Jonathan
 * @version 1.0
 * @since 12/1/2023
 * @modificado 12/1/2023
 * @returns Retorna el componente de pedidos
 * @description Componente para mostrar los pedidos del usuario
 * @version 1.0 Se agrego la funcionalidad para cancelar un pedido
 * @version 1.1 Se agrego la funcionalidad para ver los detalles de un pedido
 * @version 1.2 Se agrego la funcionalidad para mostrar el estatus de un pedido
 * @version 1.3 Se agrego la funcionalidad para mostrar la fecha de entrega de un pedido
 * @version 1.4 Se agrego la funcionalidad para mostrar la direccion de entrega de un pedido
 * @version 1.5 Se agrego la funcionalidad para mostrar el total de un pedido
 * @version 1.6 Se agrego la funcionalidad para mostrar el codigo de un pedido
 * @version 1.7 Se agrego la funcionalidad para mostrar la fecha de pedido de un pedido
 * @version 1.8 Se agrego la funcionalidad para mostrar los pedidos del usuario
 * @version 1.9 Se agrego la funcionalidad para mostrar el componente de pedidos
 * 
 */

const Pedidos = ({ pedidos, direcciones, 
                   productosOrden, ordenPedidos, 
                   getDetallePedido, cancelPedido }) => {
  return (
    <div>
      <div className="container-fluid">
        <div className="container-fluid mt-5" style={{ backgroundColor: 'white' }}>
          <h1 className="text-center">Mis Pedidos</h1>
        </div>
      </div>
      <div className="container">
        <div className="row">
          <div className="form-group col-12">
            <table className="table table-striped table-hover table-bordered" cellSpacing="0" width="100%">
              <thead>
                <tr className="text-center">
                  <th>Fecha del pedido</th>
                  <th>Fecha de entrega</th>
                  <th>Estatus</th>
                  <th>Codigo asignado</th>
                  <th>Direccion</th>
                  <th>Total Pagado</th>
                  <th>Ver Detalles</th>
                  <th>Cancelar</th>
                </tr>
              </thead>
              <tbody>
                {pedidos?.length === 0 ? (
                  <tr>
                    <td colSpan="8" className="text-center">Aun no has realizado pedidos</td>
                  </tr>
                ) : (
                  pedidos.map(pedido => (
                    <tr key={pedido.idPedido}>
                      <td className="text-center">{new Date(pedido.fechaPedido).toLocaleDateString()}</td>
                      <td className="text-center">
                        {pedido.fechaEntrega === null ? (
                          <span className="text-danger">Sin fecha de entrega</span>
                        ) : (
                          new Date(pedido.fechaEntrega).toLocaleDateString()
                        )}
                      </td>
                      <td className="text-center">
                        {pedido.estatus === '0' ? (
                          <span>Cancelado <i className="fa fa-times-circle text-danger"></i></span>
                        ) : pedido.estatus === '1' ? (
                          <span>Pendiente <i className="fa fa-clock text-warning"></i></span>
                        ) : (
                          <span>Entregado <i className="fa fa-check-circle text-success"></i></span>
                        )}
                      </td>
                      <td className="text-center"><p title="Confirma este codigo con el repartidor">{pedido.codigo}</p></td>
                      <td>
                        {direcciones.map(direccion => (
                          direccion.idDireccion === pedido.idDireccion && (
                            <span key={direccion.idDireccion} className="">
                              {direccion.calle} #{direccion.noExt}, interior {direccion.noInt}
                            </span>
                          )
                        ))}
                      </td>
                      <td className="text-center text-success">$ {pedido.total}</td>
                      <td className="text-center">
                        <button className="btn" data-bs-target="#modal" data-bs-toggle="modal" id="btnUpdate"
                          onClick={() => getDetallePedido(pedido.idPedido)}>
                          <i className="fa fa-eye"></i>
                        </button>
                      </td>
                      <td className="text-center">
                        {pedido.estatus === '0' ? (
                          <p>Cancelado <i className="fa fa-cancel"></i></p>
                        ) : (
                          <button className="btn btn-danger" id="btnDelete" onClick={() => cancelPedido(pedido.idPedido)}>
                            <i className="fas fa-trash"></i>
                          </button>
                        )}
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div className="modal fade" id="modal" tabIndex="-1" aria-labelledby="modal" aria-hidden="false">
      <div className="modal-dialog modal-fullscreen-sm-down modal-dialog-centered modal-dialog-scrollable">
        <div className="modal-content">
          <div className="modal-header">
            <h1 className="modal-title" id="modal">Detalle del pedido</h1>
            <button type="button" className="btn-close" data-bs-dismiss="modal" aria-label="Close" ></button>
          </div>
          <div className="modal-body">
            {productosOrden.map(producto => (
              <div key={producto.idProducto} className="row">
                <div className="card mb-3" style={{ maxWidth: '540px' }}>
                  <div className="row g-0">
                    <div className="col-md-4">
                      <img src={producto.foto} className="img-fluid rounded-start" alt={producto.nombreProducto} />
                    </div>
                    <div className="col-md-8">
                      <div className="card-body">
                        <p className="card-title text-center">{producto.nombreProducto}<br/> $ {producto.precioVenta} MXN</p>
                        <p className="card-text">
                          {ordenPedidos.map(orden => (
                            orden.idProducto == producto.idProducto && (
                              <span key={orden.idOrdenPedido} className="text-center">
                                Tu pedido fue de {orden.cantidad} pieza(s)<br />
                                Subtotal {orden.subtotal} pesos
                              </span>
                            )
                          ))}
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
          <div className="modal-footer">
            <button type="button" className="btn btn-success" data-bs-dismiss="modal">Aceptar</button>
          </div>
        </div>
      </div>
    </div>
    </div>
  );
};

export default Pedidos;

// muebleriaValadezFront/src/app/pedidos/pedidos.component.ts
import { Component } from '@angular/core';
import { PedidoService } from '../productos-pedido/services/pedido.service';
import { Pedido } from '../productos-pedido/interfaces/pedido.interface';
import { Observable } from 'rxjs';
import { DireccionService } from '../productos-pedido/services/address.service';
import { Direccion } from '../productos-pedido/interfaces/address.interface';

@Component({
  selector: 'app-pedidos',
  templateUrl: './pedidos.component.html',
  styleUrls: ['./pedidos.component.css']
})
export class PedidosComponent {
  constructor(private pedidosServices : PedidoService,
              private direccionService: DireccionService) {
    this.getAllPedidosCliente();
  }
  direcciones!:Observable<Direccion[]>;
  pedidos!:Observable<Pedido[]> ;

  getAllPedidosCliente(){
    var idCliente = sessionStorage.getItem('idCliente');
    // Si no existe, se asigna 0 y se convierte a numero
    const idCl = idCliente!== null ? parseInt(idCliente, 10) : 0;
    this.pedidos = this.pedidosServices.getAllPedidosCliente(idCl)
    this.direcciones = this.direccionService.getAllDireccionesCliente(idCl);
  }
}

<div class="container-fluid">
    <div class="container-fluid mt-5" style="background-color: white;">
        <h1 class="text-center">Mis Pedidos</h1>
    </div>
</div>
<div class="container">
    <div class="row">
      <div class="form-group col-12 ">
        <table
          class="table table-striped table-hover table-bordered"
          cellspacing="0"
          width="100%"
        >
          <thead>
            <tr class="text-center">              
              <th>Fecha del pedido</th>
              <th>Fecha de entrega</th>
              <th>Estatus</th>
              <th>Codigo asignado</th>
              <th>Direccion</th>
              <th>Total</th>
              <th>Ver Detalles</th>
              <th>Cancelar</th>
            </tr>
          </thead>
          <!--ng-container que valida si la lista pedidos esta vacia -->
          <ng-container *ngIf="(pedidos | async)?.length == 0">
            <tbody>
              <tr>
                <td colspan="8" class="text-center">Aun no haz realizado pedidos</td>
              </tr>
            </tbody>
          </ng-container>
          <tbody *ngFor="let pedido of pedidos | async">
            <tr>
              <td class="text-center">{{pedido.fechaPedido | date : 'dd-MM-yyyy'}}</td>
              <td class="text-center">
                <ng-container *ngIf="pedido.fechaEntrega == null">
                    <span class="text-danger">Sin fecha de entrega</span>
                </ng-container>
                {{pedido.fechaEntrega | date : 'dd-MM-yyyy'}}
              </td>
              <td class="text-center">
                <ng-container *ngIf="pedido.estatus == '0'">
                    <span>Cancelado <i class="fa fa-times-circle text-danger"></i></span>
                </ng-container>
                <ng-container *ngIf="pedido.estatus == '1'">
                    <span>Pendiente <i class="fa fa-clock text-warning"></i></span>
                </ng-container>
                <ng-container *ngIf="pedido.estatus == '2'">
                    <span>Entregado <i class="fa fa-check-circle text-success"></i></span>
                </ng-container>
              </td>
              <td class="text-center">{{pedido.codigo}}</td>
              <td >
                <ng-container *ngFor="let direccion of direcciones | async">
                    <ng-container *ngIf="direccion.idDireccion == pedido.idDireccion">
                        {{direccion.calle}} #{{direccion.noExt}}, {{direccion.noInt}}
                    </ng-container>
                </ng-container>
              </td>
              <td class="text-center">{{pedido.total | currency}}</td>
              <td class="text-center">
                <button class="btn" data-bs-target="#modal" data-bs-toggle="modal" id="btnUpdate" 
                (click)="getDetallePedido(pedido.idPedido)">
                <i class="fa fa-eye"></i>
                </button>
              </td>
              <td class="text-center">
                <ng-container *ngIf="pedido.estatus == '0' else cancelButton">
                  <p>Cancelado <i class="fa fa-cancel"></i></p>
                </ng-container>
                <ng-template #cancelButton>
                <button class="btn btn-danger" id="btnDelete" (click)="cancelPedido(pedido.idPedido)">
                  <i class="fas fa-trash"></i>
                </button>
                </ng-template>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
</div>
  <div class="modal fade" id="modal" tabindex="-1" aria-labelledby="modal" aria-hidden="false">
    <div class="modal-dialog modal-fullscreen-sm-down modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title" id="modal">Detalle del pedido</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="row" *ngFor="let producto of productosOrden | async">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                  <div class="col-md-4">
                    <img src="{{producto.foto}}" class="img-fluid rounded-start" alt="{{producto.nombreProducto}}">
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <h3 class="card-title text-center">{{producto.nombreProducto}} {{producto.precioVenta | currency}}</h3>
                      <p class="card-text">
                        <small class="text-muted" *ngFor="let orden of ordenPedidos | async">
                          <ng-container *ngIf="orden.idProducto == producto.idProducto" class="text-center">
                            <span>Tu pedido fue de {{orden.cantidad}} pieza(s)</span><br>
                            <span>Subtotal {{orden.subtotal}} pesos</span>
                          </ng-container>
                        </small>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-success" data-bs-dismiss="modal">Aceptar</button>
        </div>
      </div>
    </div>
  </div>
